kind: DaemonSet
apiVersion: apps/v1

metadata:
  name: nginx-deamon
  namespace: nginx

spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx-deamon-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-pod
          image: nginx:latest
          ports:
            - containerPort: 80

# kubectl apply -f deployment.yml
# kubectl get pods -n nginx
# kubectl get deployments -n nginx
# kubectl scale deployment/nginx-deployment -n nginx --replicas=5
# kubectl scale deployment/nginx-deployment -n nginx --replicas=1
