kind: Pod
apiVersion: v1

metadata:
  name: nginx-pod
  namespace: nginx

spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80

# use "kubectl apply -f pod.yml" to create & update the pod.yml file